### PR TITLE
Username Verification

### PR DESCRIPTION
**Pull request by joecooldoo**
In the docs: "cloud variable server rejects any username that doesn't belong to an existing Scratch account"
Can't you ask the Scratch API for the currently logged in user?

### CODE REVIEW

**Comment by joecooldoo** [comment]
P.S. I don't want to merge anything, this is a request.

**Comment by GarboMuffin** [comment]
> Can't you ask the Scratch API for the currently logged in user?

Web browsers and web standards authors have tried very hard for the last 20 years to make this impossible. If you happen to find a way, make sure to report it to each affected browser instead of me so you can get your bug bounty.

Not convinced there is a problem that needs solving anyways.

**Comment by GarboMuffin** [comment]
The existing username validation checks are designed to make it harder to put often slurs in usernames, nothing more. Along with a very long list of naughty phrases, it has proven highly effective.

**Comment by joecooldoo** [comment]
OK. It was just one of my ideas.

**Comment by GarboMuffin** [comment]
In the future you should use issues or discussions for ideas (which are designed for that) instead of pull requests (which are designed for reviewing code changes)

**Pull request closed without merging**
